<a href="https://colab.research.google.com/github/vartiens/DeepLearningTrials/blob/main/aice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DataFrame: 2차원 dictionary

In [ ]:
import numpy as np
import pandas as pd

x = pd.DataFrame({"a": [1, 2, 3], "b": [2, 3, 4]})
print(x)
print(x["a"])

   a  b
0  1  2
1  2  3
2  3  4
0    1
1    2
2    3
Name: a, dtype: int64

데이터 불러오기: pd.read_XXX
- encoding: 인코딩 지정
- usecols: 특정 열만 선택해서 가져오기
- index_col: 인덱스로 쓸 열 선택

데이터 빈도 확인: pd.crosstab
- 2가지 값에 대해 모든 경우의 수를 카운트
- index: 행, columns: 열

In [ ]:
datRead = pd.read_csv("sample_data/california_housing_train.csv", encoding = "utf8")
print(datRead)
customRead = pd.read_csv("sample_data/california_housing_train.csv", index_col = "median_house_value", usecols = ["median_house_value", "housing_median_age", "total_rooms"])
print(customRead)
pd.crosstab(index = customRead.total_rooms, columns = customRead.housing_median_age)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0
1        -114.47     34.40                19.0       7650.0          1901.0
2        -114.56     33.69                17.0        720.0           174.0
3        -114.57     33.64                14.0       1501.0           337.0
4        -114.57     33.57                20.0       1454.0           326.0
...          ...       ...                 ...          ...             ...
16995    -124.26     40.58                52.0       2217.0           394.0
16996    -124.27     40.69                36.0       2349.0           528.0
16997    -124.30     41.84                17.0       2677.0           531.0
16998    -124.30     41.80                19.0       2672.0           552.0
16999    -124.35     40.54                52.0       1820.0           300.0

       population  households  median_income  median_house_value
0          1015.0       472.0         1.4936             66900.0
1          1129.0       463.0         1.8200             80100.0
2           333.0       117.0         1.6509             85700.0
3           515.0       226.0         3.1917             73400.0
4           624.0       262.0         1.9250             65500.0
...           ...         ...            ...                 ...
16995       907.0       369.0         2.3571            111400.0
16996      1194.0       465.0         2.5179             79000.0
16997      1244.0       456.0         3.0313            103600.0
16998      1298.0       478.0         1.9797             85800.0
16999       806.0       270.0         3.0147             94600.0

[17000 rows x 9 columns]
                    housing_median_age  total_rooms
median_house_value
66900.0                           15.0       5612.0
80100.0                           19.0       7650.0
85700.0                           17.0        720.0
73400.0                           14.0       1501.0
65500.0                           20.0       1454.0
...                                ...          ...
111400.0                          52.0       2217.0
79000.0                           36.0       2349.0
103600.0                          17.0       2677.0
85800.0                           19.0       2672.0
94600.0                           52.0       1820.0

[17000 rows x 2 columns]

housing_median_age,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,...,43.0,44.0,45.0,46.0,47.0,48.0,49.0,50.0,51.0,52.0
total_rooms,,,,,,,,,,,,,,,,,,,,,
2.0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
11.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
12.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
15.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30401.0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30405.0,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
32054.0,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
32627.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37937.0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

.head(), .tail(): 시작/끝 데이터 표시

.shape: 데이터 dimension (행, 열) - index 열 제외

.columns: index 열 제외한 열 표시

.info(): 각 열의 타입, 개수, 전체 데이터 크기 등

In [ ]:
print(customRead.head(n=4))
print(datRead.tail(n=3), end = "\n\n")
print(customRead.shape, end = "\n\n")
print(customRead.columns)
print(customRead.info())

                    housing_median_age  total_rooms
median_house_value
66900.0                           15.0       5612.0
80100.0                           19.0       7650.0
85700.0                           17.0        720.0
73400.0                           14.0       1501.0
       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16997    -124.30     41.84                17.0       2677.0           531.0
16998    -124.30     41.80                19.0       2672.0           552.0
16999    -124.35     40.54                52.0       1820.0           300.0

       population  households  median_income  median_house_value
16997      1244.0       456.0         3.0313            103600.0
16998      1298.0       478.0         1.9797             85800.0
16999       806.0       270.0         3.0147             94600.0

(17000, 2)

Index(['housing_median_age', 'total_rooms'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
Index: 17000 entries, 66900.0 to 94600.0
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   housing_median_age  17000 non-null  float64
 1   total_rooms         17000 non-null  float64
dtypes: float64(2)
memory usage: 398.4 KB
None

.describe(): 각 열의 통계(평균, 표준편차, min/max, 4분위)

.dtypes: 각 열의 데이터 타입

[].value_counts(): 해당 열의 값 분포

In [ ]:
print(customRead.describe(), end = "\n\n")
print(datRead.dtypes, end = "\n\n")
print(customRead['housing_median_age'].value_counts())

       housing_median_age   total_rooms
count        17000.000000  17000.000000
mean            28.589353   2643.664412
std             12.586937   2179.947071
min              1.000000      2.000000
25%             18.000000   1462.000000
50%             29.000000   2127.000000
75%             37.000000   3151.250000
max             52.000000  37937.000000

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

housing_median_age
52.0    1052
36.0     715
35.0     692
16.0     635
17.0     576
34.0     567
33.0     513
26.0     503
18.0     478
25.0     461
32.0     458
37.0     437
15.0     416
19.0     412
28.0     400
27.0     397
24.0     389
31.0     384
30.0     384
20.0     383
23.0     382
29.0     374
21.0     373
14.0     347
22.0     323
38.0     318
42.0     308
39.0     302
44.0     296
43.0     286
13.0     249
40.0     249
45.0     235
41.0     232
10.0     226
11.0     208
5.0      199
46.0     196
12.0     192
8.0      178
47.0     175
9.0      172
4.0      161
7.0      151
48.0     135
6.0      129
50.0     112
49.0     111
2.0       49
3.0       46
51.0      32
1.0        2
Name: count, dtype: int64

Column 단위 선택: ['열 이름']

이때 여러 개를 선택할 때는 **반드시 [['항목1', '항목2']] 식으로 해줘야함**

index로 항목들의 array를 주는 형태이기 때문

slicing도 똑같이 사용 가능

In [ ]:
print(datRead[['population', 'households']])
print(datRead['median_house_value'][30:45])

       population  households
0          1015.0       472.0
1          1129.0       463.0
2           333.0       117.0
3           515.0       226.0
4           624.0       262.0
...           ...         ...
16995       907.0       369.0
16996      1194.0       465.0
16997      1244.0       456.0
16998      1298.0       478.0
16999       806.0       270.0

[17000 rows x 2 columns]
30     65800.0
31     67500.0
32    146300.0
33    113800.0
34     95800.0
35    107800.0
36     40000.0
37     88500.0
38     91200.0
39    102800.0
40     64000.0
41     84700.0
42     70100.0
43    142500.0
44     88400.0
Name: median_house_value, dtype: float64

## .loc & .iloc - 행, 열 선택

**이것은 함수가 아니다!! 접근시 대괄호 사용!!**

loc[row, col] 형태로 사용

row, col에는 레이블, 인덱스, 조건 등이 들이간다.

**만약 특정 col 전체를 선택하고 싶으면 loc[:, col] 형태로 한다**

조건에 맞는 행/열 전체, 내지는 특정 셀들이 선택된다.

이렇게 선택된 값은 하나의 변수처럼 대입, 연산 등을 수행할 수 있다.

-> 그러면 모든 값들이 동시에 바뀐다.

---

np.arange() 함수로 인덱스를 바꿀 수 있다.

이때 바꾼 인덱스 기준 -> loc

(열 선택시에도 이름 사용 가능)

그냥 0부터 시작하는 인덱스 기준 -> iloc

(열 선택시에도 인덱스 only)

In [ ]:
datRead.index = np.arange(6969, 23969)
print(datRead)
print(datRead.loc[6974, ['longitude', 'latitude']])
print(datRead.iloc[[892, 893, 894], [4, 5, 6]])

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
6969     -114.31     34.19                15.0       5612.0          1283.0
6970     -114.47     34.40                19.0       7650.0          1901.0
6971     -114.56     33.69                17.0        720.0           174.0
6972     -114.57     33.64                14.0       1501.0           337.0
6973     -114.57     33.57                20.0       1454.0           326.0
...          ...       ...                 ...          ...             ...
23964    -124.26     40.58                52.0       2217.0           394.0
23965    -124.27     40.69                36.0       2349.0           528.0
23966    -124.30     41.84                17.0       2677.0           531.0
23967    -124.30     41.80                19.0       2672.0           552.0
23968    -124.35     40.54                52.0       1820.0           300.0

       population  households  median_income  median_house_value
6969       1015.0       472.0         1.4936             66900.0
6970       1129.0       463.0         1.8200             80100.0
6971        333.0       117.0         1.6509             85700.0
6972        515.0       226.0         3.1917             73400.0
6973        624.0       262.0         1.9250             65500.0
...           ...         ...            ...                 ...
23964       907.0       369.0         2.3571            111400.0
23965      1194.0       465.0         2.5179             79000.0
23966      1244.0       456.0         3.0313            103600.0
23967      1298.0       478.0         1.9797             85800.0
23968       806.0       270.0         3.0147             94600.0

[17000 rows x 9 columns]
longitude   -114.58
latitude      33.63
Name: 6974, dtype: float64
      total_bedrooms  population  households
7861           155.0       426.0       153.0
7862           849.0      1580.0       767.0
7863           254.0       606.0       259.0

# 조건을 통한 데이터 선택

접근시 [] 안에 조건문을 집어넣으면 그걸 기준으로 필터링이 가능하다.

조건문은 따로 변수로 빼도 된다.

**주의**

Python은 &&, ||가 아니라 and, or을 쓴다.

그러나 pandas 사용 시에는 반드시 비트 연산자를 사용해야만 한다.

In [ ]:
filtered = datRead[datRead['latitude'] >= 38]
print(filtered)
cond = (datRead['housing_median_age'] < 25) & (datRead['population'] > 800)
fil2 = datRead[cond][['median_income', 'median_house_value']]
print(fil2)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16017    -118.98     38.03                15.0        991.0           277.0
16480    -119.30     38.26                19.0       3325.0           660.0
16588    -119.44     38.53                20.0       1963.0           434.0
16977    -119.78     38.69                17.0       1364.0           282.0
17195    -119.92     38.91                15.0       3831.0           625.0
...          ...       ...                 ...          ...             ...
23964    -124.26     40.58                52.0       2217.0           394.0
23965    -124.27     40.69                36.0       2349.0           528.0
23966    -124.30     41.84                17.0       2677.0           531.0
23967    -124.30     41.80                19.0       2672.0           552.0
23968    -124.35     40.54                52.0       1820.0           300.0

       population  households  median_income  median_house_value
16017       419.0       170.0         3.5469             82500.0
16480       750.0       286.0         2.9509            114800.0
16588       682.0       273.0         1.5817             97800.0
16977       338.0       152.0         2.4500            117600.0
17195       984.0       328.0         5.0718            162500.0
...           ...         ...            ...                 ...
23964       907.0       369.0         2.3571            111400.0
23965      1194.0       465.0         2.5179             79000.0
23966      1244.0       456.0         3.0313            103600.0
23967      1298.0       478.0         1.9797             85800.0
23968       806.0       270.0         3.0147             94600.0

[2546 rows x 9 columns]
       median_income  median_house_value
6969          1.4936             66900.0
6970          1.8200             80100.0
6979          2.6797             86500.0
6980          1.6250             62000.0
6983          0.8585             45000.0
...              ...                 ...
23956         2.5795             68400.0
23957         2.0074             66900.0
23960         2.4805             73200.0
23966         3.0313            103600.0
23967         1.9797             85800.0

[5333 rows x 2 columns]

열 추가하기

['새 열 이름']

기존 열로 연산해 새 열 생성 가능

.insert() 함수 사용시 위치 지정 가능

In [ ]:
filtered['newlat'] = filtered['latitude'] - 38
print(filtered)
fil3 = datRead[cond][['median_income', 'median_house_value']] # 이미 있는 열은 재삽입이 안 되므로 새로 생성
fil3.insert(2, 'houseVal_won', fil2['median_house_value'] * 1400)
print(fil3[100:1000:50])

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16017    -118.98     38.03                15.0        991.0           277.0
16480    -119.30     38.26                19.0       3325.0           660.0
16588    -119.44     38.53                20.0       1963.0           434.0
16977    -119.78     38.69                17.0       1364.0           282.0
17195    -119.92     38.91                15.0       3831.0           625.0
...          ...       ...                 ...          ...             ...
23964    -124.26     40.58                52.0       2217.0           394.0
23965    -124.27     40.69                36.0       2349.0           528.0
23966    -124.30     41.84                17.0       2677.0           531.0
23967    -124.30     41.80                19.0       2672.0           552.0
23968    -124.35     40.54                52.0       1820.0           300.0

       population  households  median_income  median_house_value  newlat
16017       419.0       170.0         3.5469             82500.0    0.03
16480       750.0       286.0         2.9509            114800.0    0.26
16588       682.0       273.0         1.5817             97800.0    0.53
16977       338.0       152.0         2.4500            117600.0    0.69
17195       984.0       328.0         5.0718            162500.0    0.91
...           ...         ...            ...                 ...     ...
23964       907.0       369.0         2.3571            111400.0    2.58
23965      1194.0       465.0         2.5179             79000.0    2.69
23966      1244.0       456.0         3.0313            103600.0    3.84
23967      1298.0       478.0         1.9797             85800.0    3.80
23968       806.0       270.0         3.0147             94600.0    2.54

[2546 rows x 10 columns]
      median_income  median_house_value  houseVal_won
7191         3.0859            134600.0   188440000.0
7270         5.4288            167800.0   234920000.0
7349         3.6027            211900.0   296660000.0
7419         2.2161             76900.0   107660000.0
7515         5.3441            193500.0   270900000.0
7630         1.7179            132000.0   184800000.0
7718         4.0484            262500.0   367500000.0
7824         2.1765            128400.0   179760000.0
7914         5.5673            288200.0   403480000.0
8020         3.8036            139600.0   195440000.0
8124         1.3194             90500.0   126700000.0
8260         3.5839            158500.0   221900000.0
8388         3.0481            210000.0   294000000.0
8487         2.1848             97900.0   137060000.0
8575         4.1953            136600.0   191240000.0
8654         3.8018            112500.0   157500000.0
8767         6.6319            269600.0   377440000.0
8914         5.5136            137100.0   191940000.0

/tmp/ipykernel_2723/1825185234.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['newlat'] = filtered['latitude'] - 38

열 삭제하기

.drop()

**이 함수는 DF 객체 자체를 수정하지 않는다**
따라서 함수의 return값을 저장해야 함

원본을 수정하려면 inplace = True 설정

axis = 1 -> 열 삭제

axis = 0 -> 행 삭제

In [ ]:
fil3_cut = fil3.drop('houseVal_won', axis = 1)
print(fil3_cut)
fil3_sex = fil3.drop(index = 8914, axis = 0)
print(fil3_sex[100:1000:50])
fil3_sex.drop('median_house_value', axis = 1, inplace = True)
print(fil3_sex[1077:1078])

       median_income  median_house_value
6969          1.4936             66900.0
6970          1.8200             80100.0
6979          2.6797             86500.0
6980          1.6250             62000.0
6983          0.8585             45000.0
...              ...                 ...
23956         2.5795             68400.0
23957         2.0074             66900.0
23960         2.4805             73200.0
23966         3.0313            103600.0
23967         1.9797             85800.0

[5333 rows x 2 columns]
      median_income  median_house_value  houseVal_won
7191         3.0859            134600.0   188440000.0
7270         5.4288            167800.0   234920000.0
7349         3.6027            211900.0   296660000.0
7419         2.2161             76900.0   107660000.0
7515         5.3441            193500.0   270900000.0
7630         1.7179            132000.0   184800000.0
7718         4.0484            262500.0   367500000.0
7824         2.1765            128400.0   179760000.0
7914         5.5673            288200.0   403480000.0
8020         3.8036            139600.0   195440000.0
8124         1.3194             90500.0   126700000.0
8260         3.5839            158500.0   221900000.0
8388         3.0481            210000.0   294000000.0
8487         2.1848             97900.0   137060000.0
8575         4.1953            136600.0   191240000.0
8654         3.8018            112500.0   157500000.0
8767         6.6319            269600.0   377440000.0
8923         3.4228            115700.0   161980000.0
      median_income  houseVal_won
9194         3.9191   142240000.0

열 이름 바꾸기: .rename

'기존이름': '새이름' 형태

행 단위 정렬하기: .sort_values

ascending = True이면 오름차순

(이 함수들 모두 원본 수정안함)

In [ ]:
renamed = datRead.rename(columns = {'population': 'humanCnt', 'median_income': 'nomuhyun'})
print(renamed.head(3))
sorted = datRead.sort_values('housing_median_age', ascending = True)
print(sorted.head(4))

      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
6969    -114.31     34.19                15.0       5612.0          1283.0
6970    -114.47     34.40                19.0       7650.0          1901.0
6971    -114.56     33.69                17.0        720.0           174.0

      humanCnt  households  nomuhyun  median_house_value
6969    1015.0       472.0    1.4936             66900.0
6970    1129.0       463.0    1.8200             80100.0
6971     333.0       117.0    1.6509             85700.0
       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
20677    -122.00     38.23                 1.0       2062.0           343.0
17962    -120.93     37.65                 1.0       2254.0           328.0
8322     -117.17     34.12                 2.0       3867.0           573.0
9442     -117.61     33.63                 2.0       4678.0           817.0

       population  households  median_income  median_house_value
20677       872.0       268.0         5.2636            191300.0
17962       402.0       112.0         4.2500            189200.0
8322       1275.0       433.0         5.4138            164400.0
9442       1970.0       712.0         6.1078            219000.0

데이터의 그룹화

한 열의 데이터를 기준으로 해서 전체 데이터를 묶을 수 있다.

Split -> Apply -> Combine

In [ ]:
groupDat = datRead.groupby('housing_median_age')
print(groupDat.groups) # 객체의 모든 값을 단순 표시

{1.0: [17962, 20677], 2.0: [7082, 7302, 8257, 8290, 8322, 8329, 8486, 8576, 8591, 8759, 8803, 8849, 9035, 9324, 9341, 9392, 9413, 9442, 9462, 9552, 9667, 9738, 9740, 9768, 9897, 9939, 11243, 12393, 12666, 15641, 15734, 17176, 17921, 18249, 18609, 18833, 18845, 19043, 19148, 19946, 20120, 20257, 20314, 20458, 20749, 21158, 22448, 22892, 23308], 3.0: [7072, 7141, 7197, 7853, 8197, 8289, 8321, 8413, 8415, 8483, 8499, 8530, 9101, 9289, 9359, 9414, 9441, 9517, 9708, 9737, 9822, 9889, 9919, 9973, 10087, 10088, 11303, 15046, 15496, 15974, 16739, 16892, 16948, 17421, 18558, 18772, 18972, 19154, 19600, 20074, 20116, 20121, 20319, 20455, 21136, 22499], 4.0: [7257, 7370, 7432, 7455, 7715, 7779, 7785, 7786, 8085, 8094, 8101, 8135, 8136, 8258, 8262, 8291, 8377, 8464, 8481, 8485, 8496, 8529, 8613, 8645, 8806, 8814, 8889, 8898, 8899, 8927, 9008, 9091, 9106, 9149, 9175, 9189, 9230, 9242, 9315, 9326, 9354, 9355, 9369, 9372, 9373, 9380, 9390, 9391, 9398, 9399, 9400, 9412, 9426, 9427, 9463, 9470, 9482, 9483, 9509, 9514, 9622, 9629, 9645, 9647, 9671, 9704, 9707, 9709, 9725, 9736, 9741, 9742, 9770, 9801, 9834, 9839, 9840, 9841, 9866, 9876, 9898, 9916, 9918, 9950, 9959, 10015, 10049, 10057, 10121, 10123, 10156, 10245, 10303, 10506, 10802, 11042, 11308, 11365, 11740, 11742, ...], 5.0: [7044, 7064, 7067, 7089, 7140, 7145, 7155, 7189, 7205, 7221, 7271, 7275, 7287, 7350, 7541, 7569, 7599, 7630, 7640, 7655, 7763, 7765, 7783, 7787, 7852, 7854, 7971, 7974, 7992, 8138, 8198, 8200, 8260, 8293, 8294, 8316, 8323, 8361, 8402, 8403, 8463, 8480, 8484, 8519, 8526, 8533, 8542, 8543, 8572, 8575, 8579, 8606, 8622, 8690, 8807, 8808, 8810, 8858, 8893, 8960, 9019, 9074, 9191, 9272, 9325, 9333, 9346, 9353, 9381, 9401, 9485, 9562, 9589, 9621, 9668, 9669, 9670, 9679, 9680, 9691, 9692, 9702, 9775, 9802, 9823, 9873, 9911, 9915, 9964, 9990, 10012, 10013, 10014, 10047, 10105, 10128, 10154, 10155, 10228, 10394, ...], 6.0: [7027, 7144, 7165, 7193, 7258, 7270, 7436, 7545, 7575, 7616, 7619, 7663, 7834, 7965, 7968, 8214, 8342, 8416, 8541, 8568, 8581, 8616, 8697, 8699, 8709, 8711, 8747, 8786, 8900, 8928, 8959, 8986, 8987, 9159, 9260, 9275, 9296, 9352, 9357, 9370, 9374, 9397, 9443, 9449, 9479, 9505, 9555, 9581, 9599, 9608, 9617, 9630, 9726, 9769, 9931, 9948, 9976, 10227, 10627, 10886, 11067, 11739, 12200, 12443, 12447, 13310, 13322, 13325, 13350, 14288, 14561, 14566, 15558, 15731, 15842, 15846, 15867, 15868, 15923, 15937, 15940, 16097, 16271, 16346, 16433, 16537, 16641, 16717, 16779, 16923, 17030, 17133, 17167, 17405, 17521, 17960, 18138, 18166, 18188, 18192, ...], 7.0: [7150, 7162, 7166, 7198, 7262, 7462, 7532, 7536, 7546, 7572, 7649, 7857, 7914, 7972, 7976, 8087, 8095, 8207, 8213, 8328, 8353, 8364, 8372, 8375, 8419, 8442, 8443, 8488, 8518, 8531, 8574, 8592, 8674, 8691, 8756, 8815, 8816, 8892, 8923, 8943, 8973, 8982, 9009, 9010, 9100, 9177, 9244, 9273, 9282, 9284, 9322, 9351, 9383, 9389, 9409, 9410, 9484, 9553, 9677, 9720, 9771, 9941, 10265, 10276, 10588, 11085, 11109, 11825, 11998, 12481, 12581, 13138, 13417, 14800, 15239, 15304, 15368, 15520, 15713, 15779, 15816, 16095, 16277, 16430, 16663, 16694, 16756, 16771, 16854, 16878, 16949, 16981, 17050, 17082, 17159, 17169, 17320, 17350, 17364, 17371, ...], 8.0: [7069, 7092, 7098, 7175, 7183, 7202, 7233, 7322, 7335, 7372, 7406, 7489, 7510, 7598, 7620, 7639, 7690, 7778, 7895, 7964, 8093, 8096, 8391, 8454, 8517, 8524, 8527, 8573, 8626, 8696, 8706, 8783, 8785, 8805, 8813, 8910, 8983, 9034, 9044, 9141, 9157, 9208, 9229, 9286, 9299, 9437, 9438, 9551, 9566, 9665, 9681, 9713, 9766, 9784, 9878, 9938, 10011, 10017, 10018, 10048, 10053, 10054, 10126, 10306, 10396, 10431, 10561, 10975, 12580, 12668, 12768, 12802, 13158, 13242, 13626, 13630, 13854, 14190, 14290, 14571, 15242, 15582, 15624, 15818, 15953, 16217, 16229, 16267, 16348, 16384, 16407, 16635, 16770, 16870, 16947, 16950, 16978, 17124, 17136, 17147, ...], 9.0: [7131, 7158, 7174, 7190, 7299, 7308, 7344, 7634, 7723, 7740, 7741, 7798, 7829, 7855, 7898, 7903, 7910, 7993, 8030, 8178, 8254, 8275, 8286, 8563, 8564, 8621, 8627, 8636, 8701, 8760, 8768, 8784, 8888, 8940, 8962, 8967, 8980, 8988, 9073, 9176, 9207, 9235, 9274, 9424, 9433, 9459, 9480, 9520, 9543, 9623, 9642, 9703, 9735, 9848, 9871, 9891, 9966, 9982, 10050, 10051, 10052, 10125, 10217, 10232, 10305, 10551, 10853, 10913, 12107, 12390, 12460, 12476, 12480, 13142, 13597, 13662, 13856, 15192, 15227, 15404, 15780, 15850, 15857, 15863, 15985, 16057, 16165, 16173, 16184, 16227, 16432, 16531, 16741, 16818, 16852, 16877, 17001, 17081, 17141, 17148, ...], 10.0: [7024, 7065, 7110, 7137, 7146, 7152, 7167, 7172, 7200, 7206, 7237, 7301, 7309, 7328, 7374, 7420, 7499, 7542, 7600, 7824, 7847, 7851, 7858, 7927, 7963, 8027, 8142, 8193, 8251, 8266, 8386, 8441, 8489, 8520, 8567, 8580, 8692, 8704, 8714, 8746, 8749, 8834, 8850, 8937, 9017, 9055, 9060, 9072, 9089, 9099, 9113, 9114, 9126, 9210, 9283, 9402, 9403, 9478, 9487, 9504, 9506, 9511, 9556, 9585, 9610, 9636, 9689, 9718, 9743, 9760, 9869, 9914, 9985, 10207, 10284, 10352, 10609, 10632, 10699, 10741, 10914, 11286, 11388, 12095, 12542, 12582, 12583, 13402, 13421, 13723, 13731, 14208, 14546, 14565, 14569, 14624, 14819, 15256, 15289, 15579, ...], 11.0: [7018, 7149, 7156, 7160, 7241, 7251, 7267, 7268, 7278, 7291, 7297, 7316, 7317, 7380, 7405, 7483, 7503, 7535, 7623, 7636, 7718, 7739, 7758, 7838, 7886, 7904, 7988, 8000, 8031, 8055, 8086, 8202, 8203, 8461, 8608, 8624, 8631, 8642, 8748, 8764, 8854, 8857, 8873, 8897, 8911, 8970, 9042, 9062, 9088, 9152, 9158, 9435, 9503, 9510, 9561, 9567, 9588, 9650, 9693, 9734, 9759, 9774, 9901, 9957, 9967, 10100, 10127, 10157, 10169, 10786, 10832, 11002, 11364, 12419, 12535, 13226, 13726, 13884, 14209, 14435, 14547, 14551, 15117, 15240, 15247, 15441, 15557, 15620, 15732, 15797, 15819, 15874, 15888, 15988, 16181, 16197, 16280, 16377, 16520, 16529, ...], 12.0: [7028, 7090, 7111, 7163, 7178, 7213, 7248, 7264, 7288, 7386, 7414, 7441, 7443, 7446, 7463, 7530, 7561, 7621, 7664, 7717, 7775, 7815, 7937, 7960, 7970, 7973, 8089, 8140, 8208, 8209, 8212, 8440, 8459, 8493, 8501, 8532, 8647, 8763, 8770, 8862, 9064, 9123, 9168, 9213, 9263, 9265, 9278, 9309, 9329, 9337, 9436, 9481, 9486, 9518, 9587, 9666, 9700, 9739, 9875, 9903, 9923, 9946, 10028, 10214, 10294, 10464, 10501, 10612, 10617, 11005, 11183, 11234, 11239, 11491, 11655, 12001, 12193, 12381, 12533, 12564, 13241, 13450, 13634, 13886, 14292, 15288, 15420, 15784, 15854, 15879, 15959, 16142, 16178, 16195, 16212, 16250, 16319, 16324, 16329, 16419, ...], 13.0: [7012, 7104, 7114, 7154, 7204, 7215, 7216, 7244, 7250, 7277, 7280, 7290, 7292, 7324, 7345, 7393, 7465, 7466, 7482, 7509, 7604, 7618, 7635, 7742, 7757, 7901, 7902, 8021, 8024, 8098, 8114, 8319, 8373, 8492, 8540, 8584, 8634, 8643, 8673, 8702, 8708, 8758, 8762, 8804, 8856, 8861, 8926, 8969, 8984, 9018, 9020, 9037, 9058, 9154, 9259, 9476, 9508, 9550, 9590, 9619, 9620, 9661, 9701, 9712, 9723, 9798, 9867, 9910, 9917, 9984, 9998, 10010, 10027, 10029, 10231, 10251, 10301, 10408, 10430, 10502, 10508, 10644, 10831, 10839, 11043, 11180, 11213, 11227, 11305, 11651, 11654, 11820, 12003, 12380, 12436, 12478, 13161, 13223, 13451, 13753, ...], 14.0: [6972, 6996, 7032, 7066, 7126, 7135, 7164, 7179, 7201, 7242, 7249, 7256, 7260, 7304, 7305, 7314, 7326, 7331, 7346, 7359, 7371, 7384, 7404, 7431, 7481, 7544, 7551, 7566, 7576, 7602, 7603, 7637, 7647, 7657, 7692, 7781, 7797, 7801, 7808, 7828, 7835, 7990, 8016, 8018, 8020, 8026, 8097, 8124, 8211, 8216, 8297, 8366, 8433, 8448, 8449, 8453, 8458, 8482, 8500, 8525, 8544, 8630, 8698, 8707, 8713, 8765, 8860, 8931, 8936, 8968, 9033, 9050, 9061, 9079, 9080, 9140, 9174, 9190, 9209, 9243, 9314, 9340, 9344, 9394, 9407, 9415, 9431, 9513, 9516, 9563, 9586, 9686, 9761, 9777, 9789, 9799, 9894, 9900, 9902, 9922, ...], 15.0: [6969, 6983, 6992, 7007, 7048, 7054, 7062, 7085, 7087, 7093, 7102, 7148, 7169, 7170, 7180, 7210, 7230, 7232, 7269, 7289, 7307, 7315, 7327, 7334, 7347, 7351, 7388, 7422, 7440, 7480, 7485, 7486, 7507, 7558, 7601, 7612, 7648, 7695, 7769, 7780, 7837, 7850, 7868, 7913, 7916, 7987, 8007, 8025, 8032, 8037, 8092, 8113, 8137, 8143, 8144, 8151, 8152, 8157, 8215, 8252, 8261, 8265, 8318, 8320, 8330, 8374, 8418, 8422, 8495, 8515, 8536, 8596, 8597, 8625, 8641, 8717, 8775, 8776, 8817, 8855, 8890, 8896, 8939, 8974, 9007, 9013, 9014, 9038, 9039, 9056, 9112, 9129, 9257, 9258, 9264, 9300, 9327, 9371, 9418, 9439, ...], 16.0: [6979, 7001, 7059, 7077, 7094, 7103, 7117, 7159, 7173, 7191, 7207, 7212, 7222, 7239, 7245, 7253, 7259, 7263, 7273, 7298, 7306, 7311, 7330, 7338, 7341, 7348, 7381, 7402, 7409, 7434, 7445, 7453, 7454, 7488, 7502, 7573, 7579, 7580, 7613, 7614, 7617, 7626, 7658, 7672, 7677, 7697, 7703, 7724, 7762, 7767, 7770, 7856, 7867, 7892, 7899, 7908, 7911, 7912, 7977, 7978, 7986, 8017, 8033, 8034, 8035, 8036, 8039, 8040, 8041, 8042, 8088, 8091, 8139, 8145, 8147, 8148, 8149, 8150, 8204, 8206, 8210, 8232, 8259, 8263, 8264, 8270, 8284, 8292, 8359, 8376, 8390, 8401, 8417, 8430, 8455, 8460, 8470, 8474, 8475, 8487, ...], 17.0: [6971, 6984, 6987, 6988, 7009, 7026, 7034, 7056, 7074, 7100, 7106, 7115, 7134, 7142, 7161, 7168, 7177, 7182, 7187, 7217, 7252, 7254, 7255, 7276, 7281, 7282, 7283, 7340, 7349, 7361, 7369, 7394, 7403, 7412, 7467, 7478, 7490, 7498, 7513, 7517, 7518, 7534, 7548, 7577, 7584, 7656, 7661, 7667, 7668, 7670, 7671, 7673, 7676, 7708, 7714, 7719, 7722, 7725, 7726, 7727, 7729, 7756, 7761, 7764, 7768, 7772, 7777, 7782, 7827, 7839, 7849, 7884, 7962, 7975, 8014, 8022, 8029, 8038, 8079, 8082, 8109, 8112, 8133, 8134, 8141, 8146, 8183, 8201, 8205, 8287, 8341, 8392, 8444, 8473, 8535, 8550, 8565, 8577, 8594, 8623, ...], 18.0: [6993, 7013, 7020, 7025, 7050, 7076, 7088, 7108, 7112, 7151, 7186, 7188, 7196, 7219, 7220, 7224, 7228, 7236, 7243, 7279, 7319, 7320, 7323, 7336, 7354, 7378, 7382, 7385, 7451, 7456, 7464, 7471, 7477, 7491, 7508, 7645, 7662, 7665, 7669, 7707, 7731, 7760, 7803, 7804, 7812, 7825, 7848, 7865, 7907, 7940, 8023, 8078, 8421, 8446, 8447, 8569, 8582, 8585, 8593, 8638, 8646, 8654, 8657, 8658, 8688, 8689, 8705, 8715, 8766, 8901, 8935, 8964, 8979, 9024, 9031, 9032, 9093, 9102, 9121, 9147, 9187, 9247, 9249, 9252, 9303, 9347, 9368, 9422, 9489, 9598, 9603, 9607, 9628, 9634, 9639, 9673, 9694, 9696, 9714, 9842, ...], 19.0: [6970, 7002, 7003, 7008, 7078, 7086, 7099, 7123, 7125, 7153, 7171, 7185, 7238, 7261, 7265, 7284, 7318, 7325, 7356, 7360, 7376, 7389, 7400, 7408, 7411, 7424, 7444, 7537, 7540, 7568, 7570, 7581, 7586, 7597, 7666, 7694, 7822, 7836, 7873, 7880, 7969, 8050, 8154, 8182, 8306, 8358, 8384, 8420, 8462, 8494, 8537, 8546, 8637, 8640, 8653, 8679, 8721, 8820, 8891, 8914, 8966, 9006, 9066, 9069, 9107, 9115, 9116, 9144, 9148, 9179, 9287, 9293, 9311, 9331, 9348, 9367, 9472, 9529, 9568, 9613, 9633, 9662, 9664, 9672, 9711, 9730, 9794, 9795, 9913, 9955, 10023, 10026, 10030, 10031, 10032, 10035, 10045, 10046, 10073, 10135, ...], 20.0: [6973, 6989, 6991, 7017, 7049, 7061, 7068, 7073, 7083, 7097, 7105, 7147, 7209, 7234, 7272, 7296, 7310, 7357, 7377, 7391, 7395, 7401, 7419, 7469, 7516, 7521, 7531, 7543, 7567, 7644, 7646, 7660, 7811, 7833, 7864, 7866, 7919, 7931, 7939, 7943, 7949, 7953, 7985, 8004, 8054, 8111, 8130, 8170, 8337, 8412, 8497, 8635, 8656, 8801, 8866, 8902, 9057, 9139, 9211, 9279, 9323, 9342, 9451, 9469, 9565, 9575, 9627, 9659, 9705, 9746, 9748, 9757, 10034, 10094, 10120, 10153, 10171, 10211, 10312, 10361, 10366, 10395, 10462, 10525, 10560, 10581, 10652, 10775, 10797, 10865, 10977, 11020, 11113, 11143, 11144, 11167, 11478, 11497, 11584, 11590, ...], 21.0: [6980, 6986, 7006, 7016, 7045, 7063, 7211, 7214, 7218, 7246, 7321, 7329, 7343, 7352, 7368, 7379, 7398, 7435, 7484, 7515, 7611, 7625, 7653, 7691, 7701, 7710, 7728, 7738, 7766, 7774, 7826, 7860, 7906, 7959, 7984, 8010, 8049, 8053, 8081, 8129, 8131, 8311, 8388, 8407, 8554, 8588, 8604, 8607, 8633, 8686, 8732, 8800, 8822, 8824, 8864, 8975, 9040, 9167, 9192, 9215, 9253, 9276, 9295, 9304, 9317, 9318, 9328, 9334, 9365, 9428, 9432, 9502, 9595, 9653, 9744, 9745, 9793, 9850, 9874, 9969, 10025, 10063, 10065, 10068, 10158, 10224, 10243, 10263, 10267, 10288, 10327, 10330, 10370, 10413, 10482, 10537, 10538, 10570, 10721, 10749, ...], 22.0: [7043, 7109, 7113, 7121, 7192, 7195, 7227, 7332, 7397, 7460, 7500, 7525, 7529, 7562, 7565, 7605, 7638, 7659, 7705, 7706, 7792, 7823, 7897, 7938, 7966, 8006, 8163, 8300, 8404, 8445, 8490, 8552, 8571, 8590, 8600, 8603, 8648, 8693, 8703, 8755, 8761, 8774, 8872, 8925, 9078, 9227, 9313, 9343, 9350, 9382, 9417, 9570, 9604, 9637, 9651, 9763, 9865, 9879, 9994, 10071, 10115, 10117, 10147, 10152, 10164, 10173, 10269, 10338, 10393, 10481, 10507, 10535, 10548, 10555, 10559, 10817, 10836, 10876, 10944, 10946, 10949, 10990, 11010, 11019, 11037, 11061, 11084, 11086, 11105, 11110, 11111, 11165, 11224, 11259, 11361, 11401, 11431, 11482, 11591, 11593, ...], 23.0: [6998, 7033, 7037, 7041, 7042, 7075, 7079, 7119, 7127, 7240, 7303, 7337, 7355, 7375, 7421, 7433, 7458, 7501, 7511, 7512, 7624, 7651, 7675, 7680, 7720, 7790, 7832, 7845, 7846, 7909, 7932, 7958, 7961, 7983, 8013, 8076, 8108, 8169, 8268, 8288, 8305, 8389, 8452, 8457, 8555, 8578, 8615, 8620, 8687, 8722, 8812, 8924, 9004, 9063, 9065, 9081, 9090, 9095, 9146, 9153, 9271, 9308, 9423, 9429, 9434, 9466, 9468, 9574, 9625, 9710, 9728, 9933, 9947, 9968, 9992, 9996, 10024, 10038, 10042, 10044, 10085, 10102, 10106, 10108, 10118, 10119, 10136, 10137, 10166, 10186, 10187, 10202, 10239, 10247, 10315, 10325, 10392, 10399, 10426, 10428, ...], 24.0: [6990, 7023, 7039, 7096, 7138, 7157, 7184, 7226, 7362, 7363, 7373, 7417, 7452, 7457, 7492, 7587, 7609, 7632, 7712, 7716, 7721, 7733, 7755, 7894, 7900, 7930, 7952, 7967, 7991, 8120, 8168, 8226, 8302, 8315, 8324, 8326, 8332, 8333, 8334, 8414, 8450, 8451, 8456, 8503, 8553, 8559, 8599, 8618, 8778, 8929, 8963, 9011, 9068, 9092, 9119, 9197, 9221, 9262, 9288, 9297, 9339, 9364, 9446, 9454, 9465, 9522, 9580, 9597, 9624, 9638, 9646, 9655, 9663, 9722, 9755, 9905, 10043, 10055, 10060, 10064, 10082, 10084, 10086, 10090, 10110, 10134, 10138, 10143, 10151, 10172, 10275, 10362, 10368, 10412, 10427, 10435, 10488, 10489, 10511, 10542, ...], 25.0: [6975, 7011, 7029, 7047, 7116, 7136, 7176, 7392, 7407, 7442, 7450, 7470, 7533, 7547, 7578, 7610, 7622, 7674, 7704, 7754, 7759, 7784, 7859, 7862, 7948, 7994, 8019, 8057, 8058, 8061, 8084, 8217, 8253, 8269, 8299, 8331, 8382, 8598, 8639, 8655, 8720, 8730, 8771, 8781, 8819, 8905, 8908, 8942, 9015, 9086, 9231, 9363, 9366, 9378, 9440, 9558, 9564, 9596, 9626, 9640, 9656, 9678, 9688, 9716, 9721, 9767, 9849, 9949, 9970, 9988, 9991, 10036, 10037, 10041, 10070, 10076, 10103, 10113, 10131, 10150, 10163, 10170, 10209, 10223, 10257, 10264, 10268, 10274, 10282, 10308, 10337, 10343, 10355, 10388, 10406, 10425, 10443, 10487, 10503, 10505, ...], 26.0: [7095, 7118, 7128, 7181, 7208, 7247, 7274, 7353, 7413, 7427, 7429, 7461, 7474, 7506, 7514, 7527, 7550, 7574, 7583, 7641, 7642, 7700, 7702, 7791, 7807, 7870, 7879, 7933, 8005, 8015, 8128, 8153, 8199, 8233, 8256, 8336, 8360, 8368, 8479, 8498, 8502, 8505, 8512, 8523, 8545, 8557, 8558, 8583, 8614, 8617, 8652, 8700, 8727, 8757, 8788, 8827, 8836, 8837, 8839, 8934, 9000, 9030, 9118, 9170, 9173, 9180, 9186, 9219, 9240, 9277, 9292, 9321, 9420, 9421, 9453, 9572, 9573, 9606, 9616, 9732, 9753, 9764, 9765, 9796, 9797, 9804, 9817, 9829, 9963, 9971, 9972, 10062, 10095, 10107, 10114, 10129, 10133, 10139, 10142, 10144, ...], 27.0: [7035, 7080, 7091, 7199, 7203, 7358, 7437, 7549, 7553, 7571, 7643, 7654, 7687, 7711, 7863, 7874, 7893, 7955, 8008, 8012, 8077, 8107, 8162, 8195, 8230, 8276, 8285, 8310, 8314, 8381, 8478, 8511, 8514, 8602, 8719, 8729, 8797, 8818, 8995, 9005, 9036, 9054, 9085, 9134, 9181, 9223, 9234, 9388, 9464, 9467, 9501, 9519, 9523, 9657, 9837, 9864, 10002, 10061, 10078, 10080, 10083, 10162, 10189, 10360, 10372, 10379, 10382, 10403, 10460, 10465, 10479, 10541, 10543, 10587, 10611, 10615, 10707, 10731, 10736, 10745, 10760, 10767, 10778, 10790, 10813, 10870, 10878, 10883, 10918, 10974, 11022, 11044, 11062, 11064, 11065, 11091, 11133, 11255, 11355, 11384, ...], 28.0: [6985, 7046, 7120, 7122, 7130, 7223, 7229, 7367, 7430, 7447, 7615, 7633, 7652, 7810, 7814, 7830, 7844, 7883, 7889, 7891, 7920, 7929, 7996, 8048, 8080, 8105, 8106, 8167, 8225, 8295, 8346, 8363, 8365, 8367, 8383, 8509, 8601, 8605, 8833, 8903, 8913, 8965, 9021, 9053, 9075, 9087, 9096, 9193, 9232, 9233, 9254, 9307, 9320, 9379, 9526, 9540, 9605, 9612, 9643, 9652, 9684, 9690, 9809, 9816, 9827, 9880, 9904, 9908, 9925, 9927, 10075, 10109, 10192, 10272, 10273, 10279, 10407, 10471, 10472, 10486, 10510, 10513, 10515, 10527, 10638, 10648, 10679, 10689, 10713, 10774, 10801, 10827, 10890, 10985, 10988, 11003, 11021, 11050, 11079, 11088, ...], 29.0: [6974, 7004, 7010, 7053, 7057, 7101, 7132, 7235, 7300, 7415, 7416, 7449, 7459, 7475, 7487, 7539, 7552, 7608, 7685, 7746, 7750, 7809, 7936, 7942, 7999, 8009, 8011, 8047, 8063, 8100, 8132, 8161, 8229, 8325, 8370, 8589, 8619, 8844, 8941, 8961, 8985, 9016, 9022, 9025, 9047, 9048, 9049, 9143, 9165, 9212, 9214, 9266, 9281, 9310, 9330, 9375, 9411, 9430, 9507, 9525, 9615, 9687, 9752, 9828, 9836, 9847, 9909, 9930, 10001, 10003, 10096, 10200, 10201, 10203, 10254, 10323, 10354, 10440, 10532, 10550, 10577, 10601, 10635, 10698, 10716, 10735, 10777, 10804, 10825, 10848, 10858, 10877, 10910, 10926, 10930, 11047, 11057, 11068, 11087, 11093, ...], 30.0: [6995, 7019, 7070, 7312, 7396, 7479, 7495, 7560, 7564, 7607, 7748, 7818, 7888, 7896, 7928, 7941, 7951, 7982, 7989, 8062, 8159, 8249, 8379, 8385, 8387, 8424, 8425, 8522, 8651, 8678, 8684, 8685, 8718, 8750, 8780, 8782, 8904, 8915, 8933, 8976, 8997, 9023, 9164, 9166, 9268, 9362, 9497, 9528, 9685, 9807, 9835, 10005, 10072, 10081, 10112, 10237, 10250, 10253, 10287, 10324, 10493, 10509, 10544, 10567, 10580, 10610, 10684, 10688, 10692, 10725, 10762, 10768, 10791, 10885, 10887, 10937, 10976, 10991, 11007, 11013, 11119, 11125, 11129, 11131, 11135, 11162, 11164, 11201, 11217, 11290, 11298, 11376, 11400, 11403, 11409, 11434, 11446, 11451, 11500, 11503, ...], 31.0: [6982, 7058, 7225, 7383, 7387, 7418, 7496, 7497, 7520, 7528, 7556, 7582, 7698, 7737, 7776, 7789, 7800, 7842, 7843, 7861, 7878, 7881, 7922, 7925, 7926, 7945, 7981, 8099, 8166, 8222, 8250, 8378, 8380, 8472, 8476, 8538, 8548, 8549, 8677, 8726, 8769, 8796, 8907, 9043, 9045, 9067, 9084, 9105, 9196, 9248, 9256, 9312, 9332, 9447, 9452, 9754, 9785, 9824, 10039, 10111, 10161, 10204, 10222, 10230, 10236, 10260, 10296, 10342, 10348, 10353, 10371, 10420, 10449, 10474, 10475, 10687, 10706, 10738, 10748, 10811, 10826, 10845, 10894, 10908, 10909, 10924, 10973, 10979, 10997, 11048, 11074, 11148, 11191, 11262, 11270, 11285, 11312, 11348, 11370, 11375, ...], 32.0: [6997, 7015, 7022, 7107, 7133, 7286, 7333, 7364, 7423, 7448, 7468, 7592, 7696, 7773, 7817, 7905, 8181, 8194, 8224, 8248, 8255, 8301, 8465, 8477, 8672, 8683, 8724, 8725, 8734, 8737, 8832, 8989, 9077, 9094, 9111, 9124, 9138, 9156, 9203, 9222, 9236, 9238, 9241, 9267, 9305, 9306, 9500, 9609, 9654, 9779, 9783, 9929, 9934, 10040, 10077, 10167, 10179, 10234, 10241, 10314, 10322, 10391, 10405, 10423, 10424, 10434, 10442, 10451, 10452, 10478, 10485, 10492, 10514, 10540, 10553, 10565, 10568, 10578, 10579, 10583, 10606, 10619, 10620, 10639, 10681, 10695, 10712, 10751, 10765, 10788, 10809, 10829, 10854, 10880, 10881, 10892, 10897, 10921, 10928, 10929, ...], 33.0: [7005, 7038, 7055, 7139, 7194, 7342, 7390, 7428, 7439, 7473, 7493, 7519, 7555, 7559, 7596, 7631, 7679, 7713, 7736, 7747, 7753, 7771, 7841, 7869, 7887, 7935, 7954, 8056, 8066, 8104, 8119, 8156, 8160, 8196, 8327, 8335, 8355, 8362, 8409, 8410, 8429, 8438, 8510, 8570, 8650, 8664, 8681, 8745, 8751, 8754, 8852, 8869, 8917, 9104, 9110, 9137, 9145, 9226, 9250, 9270, 9298, 9302, 9387, 9445, 9457, 9493, 9531, 9560, 9576, 9579, 9583, 9644, 9717, 9719, 9782, 9808, 9811, 9812, 9838, 9852, 9853, 9885, 9924, 9936, 10004, 10079, 10197, 10199, 10255, 10261, 10262, 10281, 10311, 10316, 10320, 10341, 10359, 10402, 10410, 10422, ...], 34.0: [6977, 6994, 7031, 7040, 7060, 7084, 7124, 7313, 7339, 7472, 7505, 7523, 7524, 7526, 7585, 7591, 7595, 7686, 7699, 7730, 7734, 7735, 7752, 7795, 7831, 7957, 8052, 8060, 8065, 8070, 8127, 8218, 

groupby 객체에서 함수를 적용해 통계를 구할 수 있다.

In [ ]:
print(groupDat.count()[['longitude']], end='\na==============a\n') # 각 값에 해당하는 데이터 수(모든 열)
print(groupDat.size(), end='\na==============a\n') # 해당 열 데이터의 각 값당 개수
print(groupDat.max(), end='\na==============a\n') # 각 그룹의 각 열별 최댓값
print(groupDat.min(), end='\na==============a\n') # 최솟값
print(groupDat.mean(), end='\na==============a\n') # 평균, 이외에도 std, var 등 존재

                    longitude
housing_median_age
1.0                         2
2.0                        49
3.0                        46
4.0                       161
5.0                       199
6.0                       129
7.0                       151
8.0                       178
9.0                       172
10.0                      226
11.0                      208
12.0                      192
13.0                      249
14.0                      347
15.0                      416
16.0                      635
17.0                      576
18.0                      478
19.0                      412
20.0                      383
21.0                      373
22.0                      323
23.0                      382
24.0                      389
25.0                      461
26.0                      503
27.0                      397
28.0                      400
29.0                      374
30.0                      384
31.0                      384
32.0                      458
33.0                      513
34.0                      567
35.0                      692
36.0                      715
37.0                      437
38.0                      318
39.0                      302
40.0                      249
41.0                      232
42.0                      308
43.0                      286
44.0                      296
45.0                      235
46.0                      196
47.0                      175
48.0                      135
49.0                      111
50.0                      112
51.0                       32
52.0                     1052
a==============a
housing_median_age
1.0        2
2.0       49
3.0       46
4.0      161
5.0      199
6.0      129
7.0      151
8.0      178
9.0      172
10.0     226
11.0     208
12.0     192
13.0     249
14.0     347
15.0     416
16.0     635
17.0     576
18.0     478
19.0     412
20.0     383
21.0     373
22.0     323
23.0     382
24.0     389
25.0     461
26.0     503
27.0     397
28.0     400
29.0     374
30.0     384
31.0     384
32.0     458
33.0     513
34.0     567
35.0     692
36.0     715
37.0     437
38.0     318
39.0     302
40.0     249
41.0     232
42.0     308
43.0     286
44.0     296
45.0     235
46.0     196
47.0     175
48.0     135
49.0     111
50.0     112
51.0      32
52.0    1052
dtype: int64
a==============a
                    longitude  latitude  total_rooms  total_bedrooms  \
housing_median_age
1.0                   -120.93     38.23       2254.0           343.0
2.0                   -115.80     40.58      21897.0          3513.0
3.0                   -115.60     38.77      21060.0          3559.0
4.0                   -116.76     39.00      37937.0          5471.0
5.0                   -115.55     40.60      25187.0          4386.0
6.0                   -115.52     38.73      16431.0          2640.0
7.0                   -116.31     40.60      28258.0          4407.0
8.0                   -115.59     40.61      32054.0          5290.0
9.0                   -116.22     40.62      30405.0          4095.0
10.0                  -115.52     40.67      20263.0          4952.0
11.0                  -115.51     41.75      32627.0          6445.0
12.0                  -115.53     40.92      25957.0          4798.0
13.0                  -115.50     41.32      18448.0          3474.0
14.0                  -114.57     41.54      25135.0          4819.0
15.0                  -114.31     41.78      16042.0          2888.0
16.0                  -114.60     40.93      19059.0          4183.0
17.0                  -114.56     41.84      17715.0          3630.0
18.0                  -115.22     41.95      12707.0          2793.0
19.0                  -114.47     41.86      15990.0          3093.0
20.0                  -114.57     41.82      17377.0          4457.0
21.0                  -114.60     41.95      12902.0          3039.0
22.0                  -115.55     41.68      17591.0          3680.0
23.0                  -115.37     41.70      11294.0          1995.0
24.0                  -114.73     41.03      10281.0          2823.0
25.0                  -114.58     41.86      11016.0          3179.0
26.0                  -116.00     41.21       8902.0          2055.0
27.0                  -115.54     40.98      12342.0          2630.0
28.0                  -114.65     41.86      12139.0          2873.0
29.0                  -114.58     41.36      17738.0          3114.0
30.0                  -115.37     40.77       6540.0          1564.0
31.0                  -114.61     41.50       9320.0          1827.0
32.0                  -115.37     41.15      14556.0          2077.0
33.0                  -115.46     41.74       9531.0          1583.0
34.0                  -114.59     41.79       9280.0          1914.0
35.0                  -115.38     40.88      10869.0          2961.0
36.0                  -116.56     40.78       6871.0          2477.0
37.0                  -115.60     40.79       5477.0          1980.0
38.0                  -115.38     40.79       5587.0          1295.0
39.0                  -117.07     40.79       8193.0          1747.0
40.0                  -116.98     41.78       7737.0          2158.0
41.0                  -114.59     40.88       4400.0          1130.0
42.0                  -117.07     41.78       6297.0          2293.0
43.0                  -117.01     40.79       4994.0          1646.0
44.0                  -115.73     40.87       6983.0          1584.0
45.0                  -117.12     41.43       7803.0          2154.0
46.0                  -114.60     40.78       6429.0          2610.0
47.0                  -117.10     40.87       5416.0          1271.0
48.0                  -114.61     39.51       4506.0          1342.0
49.0                  -117.10     39.44       4449.0          1197.0
50.0                  -117.11     41.73       3657.0          1095.0
51.0                  -117.15     40.17       4280.0           632.0
52.0                  -116.88     41.32       6016.0          2747.0

                    population  households  median_income  median_house_value
housing_median_age
1.0                      872.0       268.0         5.2636            191300.0
2.0                     8652.0      2873.0        10.1531            500001.0
3.0                     9623.0      3112.0        11.5199            500001.0
4.0                    16122.0      5189.0        13.4883            500001.0
5.0                    11956.0      3886.0        12.6320            500001.0
6.0                     8222.0      2553.0        13.0502            500001.0
7.0                    15037.0      4072.0        13.8093            500001.0
8.0                    15507.0      5050.0        14.9009            500001.0
9.0                    12873.0      3931.0        10.8289            500001.0
10.0                    9851.0      4616.0        12.5420            500001.0
11.0                   28566.0      6082.0        13.1477            500001.0
12.0                   12153.0      4490.0        10.0760            500001.0
13.0                    7775.0      3232.0         9.8346            500001.0
14.0                   35682.0      4769.0        15.0001            500001.0
15.0                    8997.0      2789.0        15.0001            500001.0
16.0                   10988.0      3595.0        12.0088            500001.0
17.0                    7665.0      3176.0        15.0001            500001.0
18.0                    7009.0      2552.0        11.6017            500001.0
19.0                   11272.0      2905.0        15.0000            500001.0
20.0                    7604.0      4204.0        12.2092            500001.0
21.0                    7282.0      2839.0        11.6833            500001.0
22.0                    9135.0      3522.0        11.2463            500001.0
23.0                    6330.0      1924.0        12.9792            500001.0
24.0                    7174.0      2565.0        14.5833            500001.0
25.0                    7679.0      2902.0        13.3913            500001.0
26.0                    8551.0      1822.0        15.0001            500001.0
27.0                    5023.0      1763.0        15.0001            500001.0
28.0                    6912.0      2731.0        14.4113            500001.0
29.0                   12427.0      2826.0        13.9470            500001.0
30.0                    4480.0      1536.0        12.4429            500001.0
31.0                    5666.0      1755.0        15.0001            500001.0
32.0                    5459.0      2017.0        15.0001            500001.0
33.0                    5650.0      1537.0        15.0001            500001.0
34.0                    5477.0      1789.0        15.0001            500001.0
35.0                    9879.0      2769.0        15.0001            500001.0
36.0                    4711.0      2323.0        15.0001            500001.0
37.0                    3895.0      1874.0        13.3670            500001.0
38.0                    3702.0      1253.0        12.7823            500001.0
39.0                    6852.0      1597.0        11.8603            500001.0
40.0                    4828.0      2028.0        15.0001            500001.0
41.0                    3121.0      1030.0         8.8619            500001.0
42.0                    6846.0      2156.0        15.0001            500001.0
43.0                    3920.0      1429.0        15.0001            500001.0
44.0                    3913.0      1383.0        12.4237            500001.0
45.0                    4715.0      2041.0        15.0001            500001.0
46.0                    7443.0      2406.0        15.0001            500001.0
47.0                    3348.0      1106.0         9.4590            500001.0
48.0                    3298.0      1239.0        15.0001            500001.0
49.0                    2862.0      1009.0        12.9591            500001.0
50.0                    3080.0       997.0        13.3036            500001.0
51.0                    1795.0       621.0         9.3694            500001.0
52.0                    4518.0      2538.0        15.0001            500001.0
a==============a
                    longitude  latitude  total_rooms  total_bedrooms  \
housing_median_age
1.0                   -122.00     37.65       2062.0           328.0
2.0                   -122.51     33.16         96.0            18.0
3.0                   -122.33     32.87        475.0           115.0
4.0                   -122.72     32.65          2.0             2.0
5.0                   -122.55     32.55        111.0            21.0
6.0                   -122.76     32.67         78.0            11.0
7.0                   -122.79     32.54         77.0            12.0
8.0                   -123.00     32.55         32.0             9.0
9.0                   -123.49     32.56        254.0            50.0
10.0                  -123.40     32.57         69.0            16.0
11.0                  -124.23     32.58         72.0            16.0
12.0                  -124.09     32.58         57.0            22.0
13.0                  -124.17     32.58        221.0            42.0
14.0                  -124.05     32.57        231.0            36.0
15.0                  -124.19     32.55        208.0            49.0
16.0                  -124.00     32.56         18.0             3.0
17.0                  -124.30     32.56         89.0            19.0
18.0                  -124.10     32.56        102.0            17.0
19.0                  -124.30     32.59        121.0            34.0
20.0                  -124.21     32.56         37.0            11.0
21.0                  -124.19     32.57         44.0            33.0
22.0                  -124.14     32.56        197.0            54.0
23.0                  -124.16     32.56        149.0            32.0
24.0                  -124.15     32.60         84.0            14.0
25.0                  -124.14     32.57        182.0            41.0
26.0                  -124.17     32.57         15.0             3.0
27.0                  -124.14     32.58        210.0            56.0
28.0                  -124.22     32.58         26.0             3.0
29.0                  -124.14     32.58        124.0            22.0
30.0                  -124.19     32.59         48.0            14.0
31.0                  -124.13     32.63         40.0             8.0
32.0                  -124.25     32.58        296.0            58.0
33.0                  -124.18     32.60         32.0             6.0
34.0                  -124.18     32.58         45.0            11.0
35.0                  -124.18     32.67        167.0            31.0
36.0                  -124.27     32.58         15.0             5.0
37.0                  -124.19     32.62        102.0            17.0
38.0                  -124.14     32.64         51.0            12.0
39.0                  -124.18     32.69         47.0            16.0
40.0                  -122.82     32.63         67.0            17.0
41.0                  -123.98     32.68         80.0            20.0
42.0                  -124.10     32.70        106.0            18.0
43.0                  -124.17     32.66         88.0            12.0
44.0                  -124.09     32.69        121.0            29.0
45.0                  -123.22     32.69        121.0            25.0
46.0                  -124.16     32.66         11.0             4.0
47.0                  -124.15     32.68        463.0           108.0
48.0                  -122.97     32.69        143.0            41.0
49.0                  -123.79     32.68         98.0            24.0
50.0                  -124.16     32.70        187.0            33.0
51.0                  -122.48     32.72        175.0            43.0
52.0                  -124.35     32.67          8.0             1.0

                    population  households  median_income  median_house_value
housing_median_age
1.0                      402.0       112.0         4.2500            189200.0
2.0                       30.0        16.0         1.9667             47500.0
3.0                      236.0       123.0         2.1187             83200.0
4.0                        6.0         2.0         0.5360             42500.0
5.0                       41.0        20.0         0.7526             50000.0
6.0                       27.0        10.0         0.8198             58000.0
7.0                       50.0        15.0         1.2667             56200.0
8.0                       25.0         7.0         0.8131             22500.0
9.0                       66.0        29.0         0.8952             54200.0
10.0                      48.0        16.0         0.4999             53300.0
11.0                      69.0        20.0         0.9227             50400.0
12.0                      37.0        15.0         0.8130             40000.0
13.0                      86.0        32.0         0.8288             43000.0
14.0                      88.0        31.0         1.1301             32900.0
15.0                      51.0        20.0         0.4999             32500.0
16.0                       3.0         4.0         0.4999             14999.0
17.0                      29.0        15.0         0.6825             27500.0
18.0                      55.0        21.0         0.8246             47500.0
19.0                     101.0        28.0         0.7025             14999.0
20.0                      34.0         8.0         0.8894             32500.0
21.0                      64.0        27.0         0.8571             25000.0
22.0                      98.0        42.0         0.7473             34400.0
23.0                      64.0        34.0         0.4999             30000.0
24.0                      32.0         8.0         0.6433             32500.0
25.0                      28.0        16.0         0.7990             45500.0
26.0                       8.0         3.0         0.5360             36600.0
27.0                      97.0        44.0         0.8543             40000.0
28.0                      29.0         9.0         0.4999             40900.0
29.0                      50.0        18.0         0.7069             28300.0
30.0                      20.0        13.0         0.7007             42500.0
31.0                      25.0         7.0         0.7684             34200.0
32.0                     138.0        52.0         0.8984             43100.0
33.0                      23.0        10.0         0.5360             22500.0
34.0                      36.0        13.0         0.8907             26600.0
35.0                     100.0        29.0         0.7075             39600.0
36.0                      15.0         2.0         0.4999             14999.0
37.0                      29.0        14.0         0.6831             42100.0
38.0                      41.0        10.0         0.7683             39400.0
39.0                      51.0        23.0         0.7160             17500.0
40.0                      50.0        32.0         0.9234             43000.0
41.0                      61.0        19.0         0.9782             41800.0
42.0                      40.0        25.0         0.8991             39400.0
43.0                      44.0        13.0         0.4999             46600.0
44.0                     142.0        30.0         1.1576             48300.0
45.0                      67.0        27.0         0.9337             30000.0
46.0                      13.0         5.0         0.4999             26900.0
47.0                     295.0        86.0         1.1868             49600.0
48.0                     129.0        50.0         0.8024             48600.0
49.0                      59.0        23.0         0.7068             52000.0
50.0                      76.0        35.0         1.2041             54200.0
51.0                     228.0        55.0         1.2852             51900.0
52.0                      13.0         1.0         0.4999             14999.0
a==============a
                     longitude   latitude  total_rooms  total_bedrooms  \
housing_median_age
1.0                -121.465000  37.940000  2158.000000      335.500000
2.0                -119.035306  35.410816  5237.102041      871.448980
3.0                -118.798478  35.164783  6920.326087     1190.826087
4.0                -118.805093  34.987764  6065.614907     1068.192547
5.0                -118.789497  35.095327  4926.261307      910.924623
6.0                -118.915969  35.183798  4365.062016      821.550388
7.0                -119.165497  35.627616  5672.907285     1047.350993
8.0                -119.375056  35.785899  4076.786517      779.252809
9.0                -119.324186  35.654942  3813.465116      727.401163
10.0               -119.350841  35.881681  3518.482301      681.508850
11.0               -119.517837  35.930288  3971.105769      768.932692
12.0               -119.405000  35.806458  4216.661458      838.843750
13.0               -119.406586  35.814819  3692.506024      719.670683
14.0               -119.510605  35.905159  3720.348703      719.187320
15.0               -119.471490  35.878341  3283.317308      645.492788
16.0               -119.530094  35.685748  3047.636220      593.274016
17.0               -119.597656  35.907882  3133.967014      634.760417
18.0               -119.640209  35.938054  3098.443515      624.525105
19.0               -119.541820  35.842597  3005.140777      621.519417
20.0               -119.862350  36.136449  2852.334204      601.778068
21.0               -119.560134  35.751635  3134.273458      645.608579
22.0               -119.598266  35.772879  3316.916409      683.736842
23.0               -119.590890  35.718115  2918.803665      584.424084
24.0               -119.344910  35.391054  2894.146530      604.647815
25.0               -119.426898  35.470108  2797.260304      581.260304
26.0               -119.477654  35.507038  2612.409543      523.944334

groupby는 두 개 이상의 열에 대해서도 할 수 있다.

In [ ]:
datR_newV = pd.read_csv("sample_data/california_housing_train.csv")
datR_newV['lat'] = datR_newV['latitude'].astype(int)
datR_newV = datR_newV.drop(['latitude'], axis = 1)
print(datR_newV.groupby(['housing_median_age', 'lat']).mean())

                         longitude  total_rooms  total_bedrooms   population  \
housing_median_age lat
1.0                37  -120.930000  2254.000000      328.000000   402.000000
                   38  -122.000000  2062.000000      343.000000   872.000000
2.0                33  -117.364545  5724.727273      956.863636  2154.045455
                   34  -117.895556  5311.222222      866.888889  1976.555556
                   36  -119.880000  4055.000000      735.000000  1730.000000
...                            ...          ...             ...          ...
52.0               37  -122.289449  2050.382100      449.614458  1007.282272
                   38  -121.888904  1644.767123      350.945205   724.917808
                   39  -121.591875  1295.437500      271.312500   658.500000
                   40  -123.715000  1997.214286      429.214286   936.500000
                   41  -122.090000  4019.000000      824.000000  1728.000000

                        households  median_income  median_house_value
housing_median_age lat
1.0                37   112.000000       4.250000       189200.000000
                   38   268.000000       5.263600       191300.000000
2.0                33   785.545455       5.525209       240445.590909
                   34   661.222222       4.901122       218933.333333
                   36   654.000000       4.213200        96500.000000
...                            ...            ...                 ...
52.0               37   424.008606       4.070223       308152.829604
                   38   322.520548       2.806041       149921.917808
                   39   249.437500       2.212219       104006.250000
                   40   381.000000       2.222450        75742.857143
                   41   706.000000       2.246200        62900.000000

[470 rows x 7 columns]

loc을 사용하면 원하는 인덱스의 데이터만 꺼낼 수 있다.

이때 index가 다차원으로 돼 있으면 Tuple을 사용해야만 한다.

In [ ]:
datRVgrp = datR_newV.groupby(['housing_median_age', 'lat'])
print(datRVgrp.mean().loc[[(10.0, 38), (20.0, 40)]])

                         longitude  total_rooms  total_bedrooms   population  \
housing_median_age lat
10.0               38  -121.394865  3072.459459      553.081081  1370.459459
20.0               40  -122.901111  2192.111111      477.888889   971.555556

                        households  median_income  median_house_value
housing_median_age lat
10.0               38   486.783784       4.198414       154754.054054
20.0               40   401.444444       2.487489        82266.666667

index 설정 시에도 이러한 다차원 group을 적용 가능하다.

set_index를 해놓으면 groupby 사용 시 level을 지정할 수 있다.

이 level은 먼저 세팅된 순서대로 0, 1, 2, ...로 진행한다.

값을 어떻게 주냐에 따라 순서를 바꿀 수도 있다.

이때는 반드시 index 설정 **먼저 해두고** groupby 해줘야 한다.

In [ ]:
indexedRV = datR_newV.set_index(['housing_median_age', 'lat'])
print(indexedRV.groupby(level = [1]).mean())
print(indexedRV.groupby(level = [0, 1]).std())
print(indexedRV.groupby(level = [0, 1]).aggregate([np.min, np.max])) # np.min, max는 뭐에 쓰는 거지?

      longitude  total_rooms  total_bedrooms   population  households  \
lat
32  -116.976710  2579.207948      535.341035  1406.024954  505.625693
33  -117.866054  2738.081918      557.394106  1525.261738  515.793956
34  -118.261202  2747.845484      585.216839  1589.317027  543.415099
35  -119.331439  2714.860911      550.484412  1470.690647  497.983213
36  -120.236833  2295.116667      467.852941  1336.854902  439.950000
37  -121.917361  2542.945366      506.223974  1301.756999  479.441696
38  -121.723409  2846.861888      548.029720  1356.560606  504.186480
39  -121.696138  2122.774390      424.030488   962.943089  363.398374
40  -122.833297  2131.260073      433.794872   997.871795  384.256410
41  -122.809538  2529.338462      522.600000  1175.923077  441.446154

     median_income  median_house_value
lat
32        3.615219       182376.644177
33        4.177150       222679.641608
34        3.931371       230999.153810
35        2.900046       114217.268585
36        3.051090       124988.728431
37        4.378369       253250.092688
38        3.534336       153650.466783
39        2.723252       109864.225610
40        2.523820        86905.124542
41        2.222269        72301.538462
                        longitude  total_rooms  total_bedrooms   population  \
housing_median_age lat
1.0                37         NaN          NaN             NaN          NaN
                   38         NaN          NaN             NaN          NaN
2.0                33    0.432861  5455.052094      890.798748  2029.567148
                   34    0.534208  4086.401711      599.857576  1479.290971
                   36         NaN          NaN             NaN          NaN
...                           ...          ...             ...          ...
52.0               37    0.267434   956.214248      271.077517   521.157385
                   38    0.516905   925.401812      180.442349   388.193349
                   39    0.647932   929.722035      180.529487   355.251836
                   40    1.219532  1147.706890      209.163233   373.347384
                   41         NaN          NaN             NaN          NaN

                        households  median_income  median_house_value
housing_median_age lat
1.0                37          NaN            NaN                 NaN
                   38          NaN            NaN                 NaN
2.0                33   714.092079       2.147444       138913.517439
                   34   447.039086       1.428019       109128.089876
                   36          NaN            NaN                 NaN
...                            ...            ...                 ...
52.0               37   246.978733       2.140448       130276.562953
                   38   166.651258       1.330544        58603.944327
                   39   157.602863       0.831185        41807.040376
                   40   148.512108       0.790984        19796.414372
                   41          NaN            NaN                 NaN

[470 rows x 7 columns]
                       longitude         total_rooms          total_bedrooms  \
                             min     max         min      max            min
housing_median_age lat
1.0                37    -120.93 -120.93      2254.0   2254.0          328.0
                   38    -122.00 -122.00      2062.0   2062.0          343.0
2.0                33    -117.78 -115.80        96.0  20391.0           18.0
                   34    -118.61 -117.17       966.0  11965.0          270.0
                   36    -119.88 -119.88      4055.0   4055.0          735.0
...                          ...     ...         ...      ...            ...
52.0               37    -122.62 -120.85         8.0   6016.0            1.0
                   38    -123.02 -121.27        20.0   4408.0            4.0
                   39    -123.21 -120.24       189.0   3720.0           34.0
                   40    -124.35 -120.66       661.0   5486.0          209.0
                   41    -122.09 -122.09      4019.0   4019.0          824.0

                               population         households          \
                           max        min     max        min     max
housing_median_age lat
1.0                37    328.0      402.0   402.0      112.0   112.0
                   38    343.0      872.0   872.0      268.0   268.0
2.0                33   3245.0       30.0  7305.0       16.0  2716.0
                   34   1802.0      233.0  4436.0      169.0  1367.0
                   36    735.0     1730.0  1730.0      654.0   654.0
...                        ...        ...     ...        ...     ...
52.0               37   2747.0       13.0  4518.0        1.0  2538.0
                   38    807.0       62.0  1789.0        9.0   777.0
                   39    707.0      121.0  1424.0       37.0   609.0
                   40   1044.0      392.0  1977.0      172.0   754.0
                   41    824.0     1728.0  1728.0      706.0   706.0

                       median_income          median_house_value
                                 min      max                min       max
housing_median_age lat
1.0                37         4.2500   4.2500           189200.0  189200.0
                   38         5.2636   5.2636           191300.0  191300.0
2.0                33         3.0417  10.1531            47500.0  500001.0
                   34         1.9667   6.6916           111100.0  450000.0
                   36         4.2132   4.2132            96500.0   96500.0
...                              ...      ...                ...       ...
52.0               37         0.4999  15.0001            22500.0  500001.0
                   38         0.9196   8.3380            52800.0  405800.0
                   39         0.8928   3.6250            55000.0  200000.0
                   40         0.9570   3.5345            49500.0  111400.0
                   41         2.2462   2.2462            62900.0   62900.0

[470 rows x 14 columns]

/tmp/ipykernel_2723/458405358.py:4: FutureWarning: The provided callable <function min at 0x79e12995dbc0> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  print(indexedRV.groupby(level = [0, 1]).aggregate([np.min, np.max])) # np.min, max는 뭐에 쓰는 거지?
/tmp/ipykernel_2723/458405358.py:4: FutureWarning: The provided callable <function max at 0x79e12995da80> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  print(indexedRV.groupby(level = [0, 1]).aggregate([np.min, np.max])) # np.min, max는 뭐에 쓰는 거지?

# Pivot Table

데이터 값들을 행/열 index로 사용하는 것이 가능하다.

위에서 set_index 한 것을 2차원 표로 펼치는 느낌

DataFrame의 .pivot/.pivot_table 함수로 생성 가능

둘의 차이: index 겹치는 경우 에러(pivot), 평균값(pivot_table)

겹치는 값에서는 aggfunc로 평균값 대신 다른거 쓸수도 있음(np.max, np.sum 등등)

In [ ]:
# datR_newV.pivot(columns = 'housing_median_age', index = 'lat', values = 'population')
# ValueError: Index contains duplicate entries, cannot reshape
datR_newV.pivot_table(columns = 'housing_median_age', index = 'lat', values = 'population', aggfunc = np.std)

/tmp/ipykernel_2723/3882156202.py:3: FutureWarning: The provided callable <function std at 0x79e12995e5c0> is currently using DataFrameGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  datR_newV.pivot_table(columns = 'housing_median_age', index = 'lat', values = 'population', aggfunc = np.std)

housing_median_age,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,...,43.0,44.0,45.0,46.0,47.0,48.0,49.0,50.0,51.0,52.0
lat,,,,,,,,,,,,,,,,,,,,,
32,NaN,3513.558073,3248.044983,1624.368158,1180.932809,1302.770552,1063.624224,1079.943283,546.621512,1305.381809,...,327.448076,727.721408,412.950360,481.362779,198.013468,201.222017,480.715092,148.510269,NaN,310.743584
33,2029.567148,2466.722052,2893.701147,2071.497788,1819.218490,1835.474319,2032.626989,998.294084,2197.103211,2013.930781,...,501.628215,613.712802,395.234112,466.482577,451.822555,420.367690,342.996356,335.715085,318.905158,497.559116
34,1479.290971,2490.865474,2521.982722,2687.628789,1585.866272,3368.004366,2988.793923,2518.527669,1425.137444,1794.312870,...,638.248268,534.043642,538.376312,1062.721110,578.701948,591.906718,527.314872,602.498371,387.542901,506.286309
35,NaN,NaN,1914.018565,988.689924,1222.051622,1393.183082,2276.454433,1659.583867,1497.126047,859.888190,...,400.222438,579.714896,48.083261,2440.958562,46.669048,466.690476,NaN,NaN,NaN,555.456839
36,NaN,1717.002330,940.218009,744.208304,1916.363353,448.562918,636.774904,761.413210,603.618478,5575.648896,...,647.825530,375.579811,614.029858,396.138301,199.692442,81.770003,489.616517,517.153346,120.500346,345.127968
37,454.609723,2375.312431,1986.901229,1451.728482,719.439181,2764.236551,1316.818350,1224.287037,1520.289158,1068.791620,...,421.139898,615.362637,666.682634,491.752844,490.428403,444.801667,455.104103,395.878756,382.345294,521.157385
38,2606.565520,2664.244859,2776.914264,1619.770742,1567.555735,1788.647530,1896.841525,1373.460020,1020.436796,1558.795791,...,595.838051,399.719693,403.714865,580.990899,278.382643,364.588041,309.932913,198.274821,NaN,388.193349
39,NaN,NaN,NaN,570.932862,NaN,715.155528,952.272072,392.058683,547.460058,1012.859785,...,450.775998,547.387355,7.071068,185.426535,225.171786,222.862252,156.270599,NaN,NaN,355.251836
40,NaN,NaN,NaN,NaN,NaN,236.173665,NaN,NaN,931.883551,2603.091489,...,284.385829,386.080303,NaN,NaN,40.869712,NaN,NaN,351.189764,NaN,373.347384
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

unstack: 지정된 index를 열로 이동

stack: 다시 index로 이동

In [ ]:
print(indexedRV.unstack(0))
print(indexedRV.unstack(1))

ValueError: Index contains duplicate entries, cannot reshape

데이터 병합: pd.concat

여기도 파라미터 모두 list로 묶어서 줘야함

ignore_index: 인덱스 강제 재배치 여부

axis: 어느 방향으로 붙일지 (0: 행(아래로), 1: 열(오른쪽으로))

join: 열이 안 맞을 때 처리 방법 (inner: 교집합만 남김, outer: 전부 다 남김)

verify_integrity: index 중복시 에러 표출

In [ ]:
t1 = pd.DataFrame({'col1': ['ar', 'sg', 'hg', 'mg', 'sr'], 'col2': [25, 50, 15, 40, 35]}, index = [0, 1, 2, 3, 4])
t2 = pd.DataFrame({'col1': ['ar', 'sg', 'mt', 'smg', 'rl'], 'col2': [20, 45, 55, 15, 40]}, index = [2, 3, 4, 5, 6])
print(pd.concat([t1, t2], axis = 1))
print(pd.concat([t1, t2], ignore_index = True))
print()
t3 = pd.DataFrame({'col2': ['ar', 'sg', 'mt', 'sex'], 'col3': [30, 55, 65, 69], 'col4': [16, 25, 36, 49]}, index = [2, 3, 4, 5])
print(pd.concat([t3, t2], join = 'outer'))
print(pd.concat([t3, t2], join = 'inner'))

  col1  col2 col1  col2
0   ar  25.0  NaN   NaN
1   sg  50.0  NaN   NaN
2   hg  15.0   ar  20.0
3   mg  40.0   sg  45.0
4   sr  35.0   mt  55.0
5  NaN   NaN  smg  15.0
6  NaN   NaN   rl  40.0
  col1  col2
0   ar    25
1   sg    50
2   hg    15
3   mg    40
4   sr    35
5   ar    20
6   sg    45
7   mt    55
8  smg    15
9   rl    40

  col2  col3  col4 col1
2   ar  30.0  16.0  NaN
3   sg  55.0  25.0  NaN
4   mt  65.0  36.0  NaN
5  sex  69.0  49.0  NaN
2   20   NaN   NaN   ar
3   45   NaN   NaN   sg
4   55   NaN   NaN   mt
5   15   NaN   NaN  smg
6   40   NaN   NaN   rl
  col2
2   ar
3   sg
4   mt
5  sex
2   20
3   45
4   55
5   15
6   40

merge & join - 특정 값을 기준으로 병합

on: 기준으로 쓸 열을 지정

how: 병합 방법 (inner, outer, left, right)

    inner, outer: 위와 같음, inner가 기본

    left, right: 왼쪽/오른쪽을 기준으로 병합 (그쪽에 없는 행은 다 무시)

left_index, right_index: True로 하면 설정된 인덱스를 활용

(사용시 on 제거필요)

In [ ]:
print(pd.merge(t1, t2, on = 'col1', how = 'outer'))
print(pd.merge(t2, t1, on = 'col1', how = 'left'))
tx1 = t1.set_index('col1')
tx3 = t3.set_index('col2')
print(pd.merge(tx1, tx3, how = 'right', left_index = True, right_index = True))

  col1  col2_x  col2_y
0   ar    25.0    20.0
1   hg    15.0     NaN
2   mg    40.0     NaN
3   mt     NaN    55.0
4   rl     NaN    40.0
5   sg    50.0    45.0
6  smg     NaN    15.0
7   sr    35.0     NaN
  col1  col2_x  col2_y
0   ar      20    25.0
1   sg      45    50.0
2   mt      55     NaN
3  smg      15     NaN
4   rl      40     NaN
      col2  col3  col4
col2
ar    25.0    30    16
sg    50.0    55    25
mt     NaN    65    36
sex    NaN    69    49